# Generated by Django 4.1.7 on 2023-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('EmpID', models.TextField(max_length=10)),
                ('Domine', models.TextField(max_length=20)),
            ],
        ),
    ]
